spring:
  application:
    name: backend
  datasource:
    url: jdbc:mysql://localhost:3306/onion-db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: onion-user
    password: onion1!       # ???? ????, ?? ????? ????? ??? ???? ?? ??
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update   # create, create-drop, update, validate, none
    show-sql: true       # SQL ?? ??
    properties:
      hibernate:
        format_sql: true   # SQL ?? ?? ??
        dialect: org.hibernate.dialect.MySQL8Dialect  # MySQL ??? ?? Dialect ??

  logging:
    level:
      org.hibernate.SQL: debug
      org.hibernate.type.descriptor.sql.BasicBinder: trace